### ISSUE TITLE
报错Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by zhouayi** [Seeed-Studio/sscma-example-esp32#13]
你好~
我尝试在esp32-s3-eye上跑一下`examples/fomo_detection_demo`
运行到`display->init();`的时候就会出现这个错误，不知道怎么回事

**Comment by iChizer0** [comment]
您好，这个问题可能是由于您在编译时没有正确指定 Board 信息造成的：

https://github.com/Seeed-Studio/sscma-example-esp32/blob/040a7b4ce2d6f0e1ab21407278fac9b47820a380/examples/fomo_detection_demo/cmake/CMakeLists.txt#L60-L65

需要将 `CONFIG_EL_BOARD_SEEED_XIAO_ESP32S3` 替换为 `CONFIG_EL_BOARD_ESPRESSIF_ESP32S3_EYE`，重新编译后再刷入既可。

另外我们提供了经过测试的固件：

[firmware_esp32_s3_eye_23_12_18.zip](https://github.com/Seeed-Studio/sscma-example-esp32/files/13700937/firmware_esp32_s3_eye_23_12_18.zip)

解压后使用以下指令刷入：

```
esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32s3 --no-stub write_flash --flash_mode dio --flash_size 8MB --flash_freq 80m 0x0 bootloader.bin 0x8000 partition-table.bin 0x10000 fomo_detection_demo.bin
```

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
