### ISSUE TITLE
fatal error: core/edgelab.h: No such file or directory

### ISSUE THREAD

**Issue by kxmin** [Seeed-Studio/sscma-example-esp32#14]
sscma-example-esp32/examples/mobilenetv2_classification_demo/main/app_main.cpp:4:10: fatal error: core/edgelab.h: No such file or directory
    4 | #include "core/edgelab.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
使用ESP-IDF 5.1 CMD进行idf.py build报上面的错误

**Comment by kxmin** [comment]
已经将sscma-example-esp32\examples\mobilenetv2_classification_demo\cmake\CMakeLists.txt中 CONFIG_EL_BOARD_SEEED_XIAO_ESP32S3 替换为 CONFIG_EL_BOARD_ESPRESSIF_ESP32S3_EY。

已经刷入了你们提供了经过测试的固件：
firmware_esp32_s3_eye_23_12_18.zip

**Comment by kxmin** [comment]
[errorlog.zip](https://github.com/Seeed-Studio/sscma-example-esp32/files/13858648/errorlog.zip)
错误日志见上面文件

**Comment by LynnL4** [comment]
hello,
由于我们在更新API的部分重构工作，所以导致部分DEMO可能无法正常编译通过，后续完成重构后会检查示例程序，谢谢。

**Comment by kxmin** [comment]
完成重构，检查完示例程序麻烦通知一下

**Comment by iChizer0** [comment]
您好，我们目前已经完成了初步重构，并更新了示例程序，您可以尝试最新的提交，谢谢 :)

**Comment by kxmin** [comment]
您好，我把示例程序mobilenetv2_classification_demo部署到板子ESPRESSIF_ESP32S3_EYE上，不是默认的板子SEEED_XIAO_ESP32S3，我修改了components\sscma-micro\CMakeLists.txt：-DCONFIG_EL_BOARD_SEEED_XIAO_ESP32S3 为 -DCONFIG_EL_BOARD_ESPRESSIF_ESP32S3_EYE，但是在部署到我的板子执行命令idf.py set-target esp32s3后，components\sscma-micro\CMakeLists.txt重新恢复为-DCONFIG_EL_BOARD_SEEED_XIAO_ESP32S3 ，我应该在什么地方修改板子为ESPRESSIF_ESP32S3_EYE？

**Comment by iChizer0** [comment]
@kxmin 在每个 example 工程下，有名为 cmake 的文件夹，您可以修改该文件夹下的 `CMakeLists.txt` 来指定开发板型号，这个文件在编译时被自动复制到 sscma-micro 中。举例来说，您可以在这里指定开发板型号：
https://github.com/Seeed-Studio/sscma-example-esp32/blob/eb89f309133cb7b2e07bf9124ab4f64bc1f5d30d/examples/mobilenetv2_classification_demo/cmake/CMakeLists.txt#L65
