### ISSUE TITLE
idf.py build fails due to  fatal error: esp_event.h: No such file or directory

### ISSUE THREAD

**Issue by nikhelk** [Seeed-Studio/sscma-example-esp32#17]
I am running IDF version 5.1.2  on MacOS Sonoma on a 2020 Intel MacBook Pro following the instructions to install the toolchain and I get this error on the idf.py build call:

n file included from /Users/nikhelkrishna/esp/sscma-example-esp32/components/sscma-micro/porting/espressif/el_device_esp.cpp:37:
/Users/nikhelkrishna/esp/sscma-example-esp32/components/sscma-micro/porting/espressif/el_network_esp.h:32:10: fatal error: esp_event.h: No such file or directory
   32 | #include "esp_event.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Compilation failed because el_network_esp.h (in "sscma-micro" component) includes esp_event.h, provided by esp_event component(s).
However, esp_event component(s) is not in the requirements list of "sscma-micro".
To fix this, add esp_event to REQUIRES list of idf_component_register call in /Users/nikhelkrishna/esp/sscma-example-esp32/components/sscma-micro/CMakeLists.txt.
ninja failed with exit code 1, output of the command is in the /Users/nikhelkrishna/esp/sscma-example-esp32/examples/yolo_detection_demo/build/log/idf_py_stderr_output_7789 and /Users/nikhelkrishna/esp/sscma-example-esp32/examples/yolo_detection_demo/build/log/idf_py_stdout_output_7789

**Comment by iChizer0** [comment]
Hello, please delete the `components/sscma-micro/CMakeLists.txt` file first, and then try the latest commit f90997c8cb4104a8995d277fa78790497357bb40 (run `git pull` in the root directory of the project).

I hope this solves your problem, thanks.

**Comment by nikhelk** [comment]
> Hello, please delete the `components/sscma-micro/CMakeLists.txt` file first, and then try the latest commit [4acdaa3](https://github.com/Seeed-Studio/sscma-example-esp32/commit/4acdaa3e52fe907eb46458f6b48fea499fa3d5c8) (run `git pull` in the root directory of the project).
> 
> I hope this solves your problem, thanks.

It is now saying CMakeLists.txt not found in project directory /Users/nikhelkrishna/esp/sscma-example-esp32
when I run idf.py set-target esp32s3
