### ISSUE TITLE
Differences between deploying on esp32-s3 using tflite and using tvm

### ISSUE THREAD

**Issue by shupinghu** [Seeed-Studio/sscma-example-esp32#18]
I noticed that the offcial documents in "https://docs.espressif.com/projects/esp-dl/zh_CN/latest/esp32/tutorials/deploying-models-through-tvm.html" recommended that we should use tvm to automatically quantify the model and deploy it on esp32, but ssama project use tflite. In the meanwhile, the offcial face detection model (50ms) is faster than the model in  ssama project (180ms), since the input size and structure of offcial model is not provided, I wonder whether the speed difference is caused by the different deploy method or not? Have you ever try to deploy the models using tvm? Why not we use tvm?

Thank you very much for your contribution and your answer!

**Comment by Pillar1989** [comment]
At the beginning of our project, esp officials did not provide more details on the use of tvm, and it seems that they do not now, we are very willing to integrate the tvm model.
