### ISSUE TITLE
The source train code of model provided in "model zoo"

### ISSUE THREAD

**Issue by shupinghu** [Seeed-Studio/sscma-example-esp32#19]
By infer the "yolov5_tiny_face.tflite"(the input size is 192x192) model provided in "model zoo", the time cost is 360ms, but by infer the model provided in "https://github.com/Seeed-Studio/sscma-model-zoo/blob/main/docs/en/person_Detection_Swift-YOLO_192.md"(the input size is 192x192 as well, and it's structure is yolov5_tiny as well), the time cost is 600ms.

The reason is that he model structure of "yolov5_tiny_face.tflite" is different with normal yolov5 structure, would you please provide the structure code of "yolov5_tiny_face.tflite" in "https://github.com/Seeed-Studio/ModelAssistant"?

**Comment by LynnL4** [comment]
Hi, Yes, yolov5_tiny_face uses a different network structure, I'll let you know when I upload the specific network configuration structure

**Comment by shupinghu** [comment]
> Hi, Yes, yolov5_tiny_face uses a different network structure, I'll let you know when I upload the specific network configuration structure

Thank you very much. It seems that the specific network configuration has not uploaded until today, could you please tell me the definite release time?

**Comment by LynnL4** [comment]
Hi, sorry, we've lost this config file and may not be able to provide it. can you try  96x96 swift-yolo?

**Comment by LynnL4** [comment]
Do you use this example? I will check it
https://github.com/Seeed-Studio/sscma-example-esp32/blob/main/examples/fomo_detection_demo/main/app_main.cpp

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
