### ISSUE TITLE
pre-trained model is invalid

### ISSUE THREAD

**Issue by AlexHsuYu** [Seeed-Studio/sscma-example-esp32#2]
The link about pre-trained model is invalid. Can you provide a download link  of fomo_mv2n_96.pth? thank you!

**Comment by mjq2020** [comment]
Hello, the pre-training weights of the FOMO model have not been released at present. We expect to release the pre-training model of FOMO this week. Please pay attention to our [model library](https://github.com/Seeed-Studio/EdgeLab/releases/tag/model_zoo)(https://github.com/Seeed-Studio/EdgeLab/releases/tag/model_zoo) to get the latest pre-training weights in time.

**Comment by mjq2020** [comment]
You can try to use this [pre-trained weights](https://files.seeedstudio.com/sscma/model_zoo/detection/models/fomo/COCO_Person/fomo_mobnetv2_0.35_x8_abl_coco_sha1_1bac3e8942be8040308c33fbddc14c92b80d2cbe.pth) for testing. If you have any questions, feel free to communicate with us.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
