### ISSUE TITLE
pfld_meter_demo 例程

### ISSUE THREAD

**Issue by Ca-AD** [Seeed-Studio/sscma-example-esp32#24]
你好请问pfld_meter_demo 这个例子，运行起来只是打印一些point-X Y数据，这个例子不是可以读出指针表的数据么？
请问如何才能打印s3摄像头识别到的数据？
如下所示：
打印信息：point -> x_y: [156, 127] t: [0]
preprocess: 5, run: 325, postprocess: 0
![1](https://github.com/user-attachments/assets/0af6d980-73c4-4b97-9f07-c401b89b7efb)

**Comment by LynnL4** [comment]
hi，该模型只是读取指针尾部的坐标信息，你可以根据起点和终点的信息，通过计算获取指针的表数

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
