### ISSUE TITLE
我想使用ESP32-S3-Korvo-2来运行fomo_detection_demo例程，需要修改什么地方

### ISSUE THREAD

**Issue by monskate** [Seeed-Studio/sscma-example-esp32#26]
我修改了摄像头引脚配置但是运行程序无反应
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x28 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x18dc
load:0x403c9700,len:0x4
load:0x403c9704,len:0xd88
load:0x403cc700,len:0x2fa0
entry 0x403c9934
[0;32mI (27) boot: ESP-IDF v5.1.4 2nd stage bootloader[0m
[0;32mI (27) boot: compile time Oct  9 2024 14:28:08[0m
[0;32mI (27) boot: Multicore bootloader[0m
[0;32mI (30) boot: chip revision: v0.2[0m
[0;32mI (34) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (39) boot.esp32s3: Boot SPI Speed : 80MHz[0m
[0;32mI (44) boot.esp32s3: SPI Mode       : QIO[0m
[0;32mI (49) boot.esp32s3: SPI Flash Size : 8MB[0m
[0;32mI (53) boot: Enabling RNG early entropy source...[0m
[0;32mI (59) boot: Partition Table:[0m
[0;32mI (62) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (70) boot:  0 factory          factory app      00 00 00010000 003bc000[0m
[0;32mI (77) boot:  1 nvs              WiFi data        01 02 003cc000 00004000[0m
[0;32mI (84) boot:  2 fr               Unknown data     01 06 003d0000 00020000[0m
[0;32mI (92) boot:  3 db               Unknown data     01 06 003f0000 00010000[0m
[0;32mI (99) boot:  4 models           Unknown data     01 06 00400000 00400000[0m
[0;32mI (107) boot: End of partition table[0m
[0;32mI (111) esp_image: segment 0: paddr=00010020 vaddr=3c0e0020 size=778dch (489692) map[0m
[0;32mI (194) esp_image: segment 1: paddr=00087904 vaddr=3fc9c200 size=05b98h ( 23448) load[0m
[0;32mI (198) esp_image: segment 2: paddr=0008d4a4 vaddr=40374000 size=02b74h ( 11124) load[0m
[0;32mI (202) esp_image: segment 3: paddr=00090020 vaddr=42000020 size=df3e0h (914400) map[0m
[0;32mI (347) esp_image: segment 4: paddr=0016f408 vaddr=40376b74 size=15604h ( 87556) load[0m
[0;32mI (374) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (374) boot: Disabling RNG early entropy source...[0m
[0;32mI (375) cpu_start: Multicore app[0m
[0;32mI (379) octal_psram: vendor id    : 0x0d (AP)[0m
[0;32mI (383) octal_psram: dev id       : 0x02 (generation 3)[0m
[0;32mI (389) octal_psram: density      : 0x03 (64 Mbit)[0m
[0;32mI (395) octal_psram: good-die     : 0x01 (Pass)[0m
[0;32mI (400) octal_psram: Latency      : 0x01 (Fixed)[0m
[0;32mI (405) octal_psram: VCC          : 0x01 (3V)[0m
[0;32mI (410) octal_psram: SRF          : 0x01 (Fast Refresh)[0m
[0;32mI (416) octal_psram: BurstType    : 0x01 (Hybrid Wrap)[0m
[0;32mI (422) octal_psram: BurstLen     : 0x01 (32 Byte)[0m
[0;32mI (427) octal_psram: Readlatency  : 0x02 (10 cycles@Fixed)[0m
[0;32mI (434) octal_psram: DriveStrength: 0x00 (1/1)[0m
[0;32mI (439) MSPI Timing: PSRAM timing tuning index: 5[0m
[0;32mI (444) esp_psram: Found 8MB PSRAM device[0m
[0;32mI (449) esp_psram: Speed: 80MHz[0m
[0;32mI (453) cpu_start: Pro cpu up.[0m
[0;32mI (456) cpu_start: Starting app cpu, entry point is 0x403757d4[0m

**Comment by monskate** [comment]
> 您好,很抱歉我们无法从您提供的日志中定位问题,如果方便的话,请告知我们您使用的摄像头型号和您调整后的引脚配置.
> 
> 此外,我们建议你修改 `examples/fomo_detection_demo/main/app_main.cpp` 中关于 `Display` 的代码,将和 display 相关的代码注释即可.

您好，我使用的是ov2640,引脚为：
#define CAMERA_PIN_PWDN              -1
#define CAMERA_PIN_RESET             -1

#define CAMERA_PIN_VSYNC             21
#define CAMERA_PIN_HREF              38
#define CAMERA_PIN_PCLK              11
#define CAMERA_PIN_XCLK              40

#define CAMERA_PIN_SIOD              17
#define CAMERA_PIN_SIOC              18

#define CAMERA_PIN_D0                13
#define CAMERA_PIN_D1                47
#define CAMERA_PIN_D2                14
#define CAMERA_PIN_D3                3
#define CAMERA_PIN_D4                12
#define CAMERA_PIN_D5                42
#define CAMERA_PIN_D6                41
#define CAMERA_PIN_D7                39

我在尝试注释display

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
