### ISSUE TITLE
FOMO模型训练差异

### ISSUE THREAD

**Issue by pancake1216** [Seeed-Studio/sscma-example-esp32#3]
我参照README相关文件，进行FOMO目标检测模型训练，不过训练模型结果有差导致辨识效果不佳，下方为结果照片与训练模型，想请问是否哪里有出问题?

![image](https://user-images.githubusercontent.com/127167397/223305096-08709e02-f1b4-439a-8491-fcdc178fb77f.png)

[model.zip](https://github.com/Seeed-Studio/edgelab-example-esp32/files/10904628/model.zip)

**Comment by mjq2020** [comment]
你好，这是缺少预训练权重的问题。目前FOMO模型的预训练权重并没有发布，我们预计这周会发布FOMO的预训练模型，请关注我们的[模型库](https://github.com/Seeed-Studio/EdgeLab/releases/tag/model_zoo)以及时获取最新发布的预训练权重。

**Comment by mjq2020** [comment]
你好，这是缺少预训练权重的问题。目前FOMO模型的预训练权重并没有发布，我们预计这周会发布FOMO的预训练模型，请关注我们的[模型库](https://github.com/Seeed-Studio/EdgeLab/releases/tag/model_zoo)以及时获取最新发布的预训练权重。

**Comment by LynnL4** [comment]
Hi, 在没有预训练的情况下可以通过适当的增加训练epoch的值，获得更好的结果。操作如下
- 拉取最新的 EdgeLab、 edgelab-example-esp32
- 更改配置文件 增加 epoch
可以通过更改 [fomo_mobnetv2_x8_custom.py](https://edgelab.readthedocs.io/en/latest/examples/edgelab-example-esp32/fomo.html#prepare-the-configuration-file) 中 `epochs` 参数 这里建议为 **70**
- 执行以下命令进行训练
` python tools/train.py mmdet /home/hongtai/EdgeLab/configs/fomo/fomo_mobnetv2_x8_custom.py`
- 后续的操作与[docs](https://edgelab.readthedocs.io/en/latest/examples/edgelab-example-esp32/fomo.html#prepare-the-configuration-file)一致

**Comment by LynnL4** [comment]
hi, 还有其它的问题吗，我们正在更新sscma-micro，欢迎到该仓库提交建议
https://github.com/Seeed-Studio/SSCMA-Micro

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
